"""Blacklists for filtering out junk domains and emails."""
from __future__ import annotations

# Domains we never want to add as prospects (aggregators, platforms, etc.)
DOMAIN_BLACKLIST: set[str] = {
    "google.com",
    "youtube.com",
    "facebook.com",
    "twitter.com",
    "x.com",
    "linkedin.com",
    "instagram.com",
    "wikipedia.org",
    "reddit.com",
    "quora.com",
    "medium.com",
    "github.com",
    "stackoverflow.com",
    "amazon.com",
    "ebay.com",
    "apple.com",
    "microsoft.com",
    "play.google.com",
    "apps.apple.com",
    "pinterest.com",
    "tumblr.com",
    "tiktok.com",
    "t.me",
    "discord.gg",
    "discord.com",
    "bit.ly",
    "tinyurl.com",
    "forbes.com",
    "bloomberg.com",
    "reuters.com",
    "techcrunch.com",
    "cnbc.com",
    "indeed.com",
    "glassdoor.com",
    "crunchbase.com",
    "bbb.org",
    "trustpilot.com",
    "yelp.com",
    "businesswire.com",
    "prnewswire.com",
}

# Email local-parts / domains to reject
EMAIL_BLACKLIST_SUBSTRINGS: set[str] = {
    "example.com",
    "example.org",
    "domain.com",
    "yourdomain",
    "youremail",
    "test@test",
    "email@email",
    "noreply",
    "no-reply",
    "donotreply",
    "sentry.io",
    "wixpress.com",
    "godaddy.com",
    "cloudflare.com",
    "@2x",
    "@3x",
    ".png",
    ".jpg",
    ".jpeg",
    ".gif",
    ".svg",
    ".webp",
}

# Prefer these email prefixes when picking a primary email
PREFERRED_EMAIL_PREFIXES: list[str] = [
    "partner",
    "partnership",
    "partnerships",
    "affiliate",
    "affiliates",
    "marketing",
    "media",
    "advertising",
    "advertise",
    "bd",
    "biz",
    "business",
    "hello",
    "contact",
    "info",
    "sales",
]

# Affiliate program indicator phrases
AFFILIATE_INDICATORS: list[str] = [
    "affiliate program",
    "partner program",
    "become a partner",
    "affiliate sign up",
    "referral program",
    "earn commissions",
    "affiliate dashboard",
    "partner with us",
    "media partnership",
    "influencer program",
    "ambassador program",
    "affiliate terms",
    "revenue share",
    "cpa program",
    "cost per acquisition",
    "become an affiliate",
]
